baseURL = "https://www.gbrl.work"
languageCode = "pt-br"
title = "gbrlpires | design visual e ilustração"
summaryLength = 20

[menu]
  [[menu.main]]
    identifier = "projetos"
    name = "projetos"
    url = "/projetos/"
    weight = 1

    [[menu.main]]
      identifier = "sobre"
      name = "sobre"
      url = "/sobre/"
      weight = 2

    [[menu.main]]
      identifier = "blog"
      name = "blog"
      url = "/blog/"
      weight = 3

    [[menu.main]]
      identifier = "notas"
      name = "notas"
      url = "/notas/"
      weight = 4

    [[menu.main]]
      identifier = "lab"
      name = "lab"
      url = "/lab/"
      weight = 5

    [[menu.main]]
      identifier = "rss"
      name = "rss"
      url = "/rss.xml/"
      weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"
  colab = "colabs"
  author = "gbrlpires"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[services]
  [services.rss]
    limit = 20

  # Linha abaixo foi adicionada para consertar a indentação na renderização da página rss.xml causada pelo --minify na hora do build 
  # em netlify.toml apaguei o --minify junto da flag [build] 
[minify]
   disableXML = true
  minifyOutput = true

