baseURL = "https://joyful-lily-300459.netlify.app/"
languageCode = "pt-br"
title = "gbrlpires"
summaryLength = 20

[menu]
  [[menu.main]]
    identifier = "projetos"
    name = "projetos"
    url = "/projetos/"
    weight = 1

    [[menu.main]]
      identifier = "sobre"
      name = "sobre"
      url = "/sobre/"
      weight = 2

    [[menu.main]]
      identifier = "blog"
      name = "blog"
      url = "/blog/"
      weight = 3

    [[menu.main]]
      identifier = "wiki"
      name = "wiki"
      url = "/wiki/"
      weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"
  colab = "colabs"
  author = "gbrlpires"
